### ISSUE TITLE
Album Art in Presence

### ISSUE THREAD

**Issue by PatrickD1985** [AB-Law/Apple-Discord-Rich-Presence#3]
Hi there, first of thanks for making this. 

Getting a decent working RP which actually works decent with Apple Music and Discord really seems to be a pain (sadly neither Apple or Discord seem keen on doing it themselves).

I was wondering if album art could become an option in showing this in the Rich Presence on Discord.
Spotify uses such an approach and it's just really the on thing I think this is missing that would make it even better.

Then again i don't know anything of the technical limitations there are when it comes to this.
Here is hoping you would at least consider this.

**Comment by AB-Law** [comment]
Hey Patrick, sorry for the late response.
I'd love to do what you are suggesting, but Discord has placed limitations on what images can be shown in the icon. It only shows icons which have already been uploaded by me on their developer application page. This restriction prevents the icon changing to match the album art of the song currently being played.
If they allow a way to do this, I will start working on a way to implement this.
