### ISSUE TITLE
SyntaxError when launching the python script

### ISSUE THREAD

**Issue by ghost** [AB-Law/Apple-Discord-Rich-Presence#4]
**Describe the bug**
When executing `python discord-apple_music.py`, I get:
```console
SyntaxError: Non-ASCII character '\xe2' in file discord-apple_music.py on line 62, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**To Reproduce**
1. Clone the repo through terminal
2. Cd into the repo folder
3. Enter `pip install -r requirements.txt`
4. Enter `python discord-apple_music.py`
5. See error

**Expected behavior**
It should've started the Apple Music Discord Rich Presence application.

**Desktop**
 - OS: macOS Big Sur, 11.3.1 (20E241)
 - Browser: Safari
 - Version: 14.1

**Comment by AB-Law** [comment]
Sorry for the late reply.
Try running the file by using `python3 discord-apple_music.py` instead and let me know if you get the same error?
